"""create species table

Revision ID: 3751d9d794c4
Revises: f028ca4adbd6
Create Date: 2026-02-03 09:31:13.293524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3751d9d794c4'
down_revision: Union[str, Sequence[str], None] = 'f028ca4adbd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('average_height', sa.String(), nullable=True),
    sa.Column('skin_colors', sa.String(), nullable=True),
    sa.Column('hair_colors', sa.String(), nullable=True),
    sa.Column('eye_colors', sa.String(), nullable=True),
    sa.Column('average_lifespan', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('homeworld_url', sa.String(), nullable=True),
    sa.Column('people', sa.JSON(), nullable=False),
    sa.Column('films', sa.JSON(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('species')
    # ### end Alembic commands ###
