"""create film_characterr table

Revision ID: b55d1c87fb54
Revises: 1166f7ec7ac4
Create Date: 2026-02-03 15:57:55.528796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b55d1c87fb54'
down_revision: Union[str, Sequence[str], None] = '1166f7ec7ac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('film_characterr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.Column('characterr_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['characterr_id'], ['characterr.id'], ),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('film_characterr')
    # ### end Alembic commands ###
