"""add films and species to characterr

Revision ID: f028ca4adbd6
Revises: e95976393490
Create Date: 2026-02-02 23:37:16.143489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f028ca4adbd6'
down_revision: Union[str, Sequence[str], None] = 'e95976393490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characterr', sa.Column('films', sa.JSON(), nullable=False))
    op.add_column('characterr', sa.Column('species', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characterr', 'species')
    op.drop_column('characterr', 'films')
    # ### end Alembic commands ###
